import eslint from '@eslint/js';
import prettier from 'eslint-config-prettier';
import importX from 'eslint-plugin-import-x';
import tseslint from 'typescript-eslint';

// Flat-config port of the old .eslintrc.base.json (ESLint 7 / typescript-eslint 4 era).
// Rule intent preserved 1:1, including the deliberate offs; import/* rules moved to
// eslint-plugin-import-x (eslint-plugin-import has no ESLint 10 support).
export default tseslint.config(
	{
		ignores: ['dist/**', 'out/**', 'node_modules/**', '.vscode-test/**', '**/*.d.ts', '*.js', 'scripts/**'],
	},
	eslint.configs.recommended,
	...tseslint.configs.recommendedTypeChecked,
	importX.flatConfigs.recommended,
	importX.flatConfigs.typescript,
	{
		languageOptions: {
			parserOptions: {
				// Not projectService: webviews/tests are separate tsconfig projects the service
				// won't discover from the root; tsconfig.eslint.json spans all linted files.
				project: './tsconfig.eslint.json',
				tsconfigRootDir: import.meta.dirname,
			},
		},
		linterOptions: {
			reportUnusedDisableDirectives: 'warn',
		},
		settings: {
			'import-x/resolver': {
				typescript: {
					project: './tsconfig.eslint.json',
				},
			},
		},
		rules: {
			'new-parens': 'error',
			'no-async-promise-executor': 'off',
			'no-console': 'off',
			'no-constant-condition': ['warn', { checkLoops: false }],
			'no-caller': 'error',
			'no-case-declarations': 'off',
			'no-debugger': 'warn',
			'no-dupe-class-members': 'off',
			'no-duplicate-imports': 'error',
			'no-else-return': 'off',
			'no-empty': 'off',
			'no-eval': 'error',
			'no-ex-assign': 'warn',
			'no-extend-native': 'error',
			'no-extra-bind': 'error',
			'no-extra-boolean-cast': 'off',
			'no-floating-decimal': 'error',
			'no-implicit-coercion': 'off',
			'no-implied-eval': 'error',
			'no-inner-declarations': 'off',
			'no-lone-blocks': 'error',
			'no-lonely-if': 'off',
			'no-loop-func': 'error',
			'no-multi-spaces': 'off',
			'no-prototype-builtins': 'off',
			'no-return-assign': 'error',
			'no-return-await': 'off',
			'no-self-compare': 'error',
			'no-sequences': 'error',
			'no-template-curly-in-string': 'warn',
			'no-throw-literal': 'error',
			'no-unmodified-loop-condition': 'warn',
			'no-unneeded-ternary': 'error',
			'no-use-before-define': 'off',
			'no-useless-call': 'error',
			'no-useless-catch': 'error',
			'no-useless-computed-key': 'error',
			'no-useless-concat': 'error',
			'no-useless-escape': 'off',
			'no-useless-rename': 'error',
			'no-useless-return': 'off',
			'no-var': 'error',
			'no-with': 'error',
			'object-shorthand': 'off',
			'one-var': 'off',
			'prefer-arrow-callback': 'off',
			'prefer-const': 'off',
			'prefer-numeric-literals': 'error',
			'prefer-object-spread': 'error',
			'prefer-rest-params': 'error',
			'prefer-spread': 'error',
			'prefer-template': 'off',
			quotes: ['error', 'single', { avoidEscape: true, allowTemplateLiterals: true }],
			'require-atomic-updates': 'off',
			semi: ['error', 'always'],
			'semi-style': ['error', 'last'],
			'sort-imports': [
				'error',
				{
					ignoreCase: true,
					ignoreDeclarationSort: true,
					ignoreMemberSort: false,
					memberSyntaxSortOrder: ['none', 'all', 'multiple', 'single'],
				},
			],
			yoda: 'error',
			'import-x/export': 'off',
			// json: require('../package.json') reads need their extension
			'import-x/extensions': ['error', 'never', { json: 'always' }],
			'import-x/named': 'off',
			'import-x/namespace': 'off',
			'import-x/newline-after-import': 'warn',
			'import-x/no-cycle': 'off',
			'import-x/no-dynamic-require': 'error',
			'import-x/no-default-export': 'off',
			'import-x/no-duplicates': 'error',
			'import-x/no-self-import': 'error',
			'import-x/no-unresolved': ['warn', { ignore: ['vscode', 'ghpr', 'git', 'extensionApi'] }],
			'import-x/order': [
				'warn',
				{
					groups: ['builtin', 'external', 'internal', ['parent', 'sibling', 'index']],
					'newlines-between': 'ignore',
					alphabetize: {
						order: 'asc',
						caseInsensitive: true,
					},
				},
			],
			'@typescript-eslint/await-thenable': 'error',
			'@typescript-eslint/consistent-type-assertions': [
				'warn',
				{
					assertionStyle: 'as',
					objectLiteralTypeAssertions: 'allow-as-parameter',
				},
			],
			'@typescript-eslint/explicit-function-return-type': 'off',
			'@typescript-eslint/explicit-member-accessibility': 'off',
			'@typescript-eslint/explicit-module-boundary-types': 'off',
			'@typescript-eslint/no-empty-function': 'off',
			'@typescript-eslint/no-empty-interface': 'error',
			'@typescript-eslint/no-explicit-any': 'off',
			'@typescript-eslint/no-floating-promises': 'off',
			'@typescript-eslint/no-implied-eval': 'error',
			'@typescript-eslint/no-inferrable-types': 'off',
			'@typescript-eslint/no-misused-promises': ['error', { checksConditionals: false, checksVoidReturn: false }],
			'@typescript-eslint/no-namespace': 'off',
			'@typescript-eslint/no-non-null-assertion': 'off',
			// require() is load-bearing here: node polyfills, dynamic vsls, package.json reads
			'@typescript-eslint/no-require-imports': 'off',
			// TODO: 21 pre-existing numeric-enum comparisons (ADO API enums vs literals); tighten separately
			'@typescript-eslint/no-unsafe-enum-comparison': 'off',
			'@typescript-eslint/no-this-alias': 'off',
			'@typescript-eslint/no-unnecessary-condition': 'off',
			'@typescript-eslint/no-unnecessary-type-assertion': 'off',
			'@typescript-eslint/no-unsafe-assignment': 'off',
			'@typescript-eslint/no-unsafe-argument': 'off',
			'@typescript-eslint/no-unsafe-call': 'off',
			'@typescript-eslint/no-unsafe-member-access': 'off',
			'@typescript-eslint/no-unsafe-return': 'off',
			'@typescript-eslint/no-unused-expressions': ['warn', { allowShortCircuit: true }],
			'@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
			'@typescript-eslint/no-use-before-define': 'off',
			'@typescript-eslint/prefer-regexp-exec': 'off',
			'@typescript-eslint/prefer-nullish-coalescing': 'off',
			'@typescript-eslint/prefer-optional-chain': 'off',
			'@typescript-eslint/require-await': 'off',
			'@typescript-eslint/restrict-plus-operands': 'error',
			'@typescript-eslint/restrict-template-expressions': 'off',
			'@typescript-eslint/strict-boolean-expressions': 'off',
			'@typescript-eslint/unbound-method': 'off',
		},
	},
	prettier,
);
